<a href="https://colab.research.google.com/github/Candida18/Python/blob/main/8960_Candida_Practical_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Name : Candida Ruth Noronha**

**Class : SE COMPS B**

**Roll No. : 8960**

**Title : Python Experiment 10**

**Aim:**

To explore Numpy arrays and its operation

In [ ]:
import numpy as np
  
R = int(input(" Enter the number of rows : "))
C = int(input(" Enter the number of columns : "))
  
print("\n Enter the entries rowise : ")
  
# User input of entries in a 
# single line separated by space
entries = list(map(int, input().split()))
  
# For printing the matrix
matrix = np.array(entries).reshape(R, C)
print("\n",matrix)

print("\n------------------------------------------------------------------------------------------------\n");

print("\n 1. Slicing multidimentional array\n 2. Flipping the order of the axes of an multidimentional array\n 3. Exit\n")

while(True):
  print("\n------------------------------------------------------------------------------------------------\n");
  choice = int(input(" Enter the choice : "))

  if(choice == 1):
    print("\n For Slicing w.r.t. Row \n")
    rfrom = int(input(" From Index : "))
    rto = int(input(" To Index : "))

    print("\n For Slicing w.r.t. Column \n")
    cfrom = int(input(" From Index : "))
    cto = int(input(" To Index : "))

    print("\n The sliced multidimentional array : \n")
    print(matrix[rfrom:rto, cfrom:cto])
  
  elif(choice == 2):
    #Transpose of an array.
    print("\n Transpose of the matrix : \n")
    arrayT = np.transpose(matrix)
    print(arrayT)

    
    # Flip array in the left/right direction.
    print("\n Flipped matrix in the left/right direction : \n")
    arrayFlr = np.fliplr(matrix)
    print(arrayFlr)

    
    # Flip array in the up/down direction.
    print("\n Flipped matrix in the up/down direction : \n")
    arrayFud = np.flipud(matrix)
    print(arrayFud)
    
    
    # Rotate an array by 90 degrees in the plane specified by axes.
    print("\n Rotated matrix by 90 degrees in the plane specified by axes : \n")
    arrayRot90 = np.rot90(matrix)
    print(arrayRot90)

  elif(choice == 3):
    print("\n Exiting !")
    break


 



 Enter the number of rows : 3
 Enter the number of columns : 3

 Enter the entries rowise : 
1 2 3 4 5 6 7 8 9

 [[1 2 3]
 [4 5 6]
 [7 8 9]]

------------------------------------------------------------------------------------------------


 1. Slicing multidimentional array
 2. Flipping the order of the axes of an multidimentional array
 3. Exit


------------------------------------------------------------------------------------------------

 Enter the choice : 1

 For Slicing w.r.t. Row 

 From Index : 1
 To Index : 3

 For Slicing w.r.t. Column 

 From Index : 0
 To Index : 3

 The sliced multidimentional array : 

[[4 5 6]
 [7 8 9]]

------------------------------------------------------------------------------------------------

 Enter the choice : 2

 Transpose of the matrix : 

[[1 4 7]
 [2 5 8]
 [3 6 9]]

 Flipped matrix in the left/right direction : 

[[3 2 1]
 [6 5 4]
 [9 8 7]]

 Flipped matrix in the up/down direction : 

[[7 8 9]
 [4 5 6]
 [1 2 3]]

 Rotated matrix by 90 